
- name: Lookup
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Create one text file
      copy:
        content: |
          This is a test content in the file
          A second line
          .
        dest: ~/mytest1.txt


    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html

    - name: Load the contents of the file in a variable
      set_fact:
        myvar1: "{{ lookup('file', '~/mytest1.txt') }}"   # CAUTION: lookup is executed on the LOCAL machine


    - name: Print the variable
      debug:
        var: myvar1




#============================ SEE ALSO ===============================================

# Lookups
# https://docs.ansible.com/ansible/latest/plugins/lookup.html
