
- name: Variable scope (play 2)
  hosts: localhost
  gather_facts: false

  vars:
    tmpvar2: This is a second variable 

  tasks:

    - name: Define a variable in the global scope
      set_fact:
        tmpvar1: This is a test




- name: Variable scope (play 2)
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Print variable 1
      debug:
        var: tmpvar1          # this variable is defined in the global scope

    - name: Print variable 2
      debug:
        var: tmpvar2          # this variable exists only in the first play
