---

- name: Copy haproxy configuration file
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    validate: "haproxy -c -V -f %s"
  notify: "Restart haproxy service"
  