
- name: Loop with loop_control
  hosts: localhost
  gather_facts: false

  vars:
    remote_files:
      - file1.txt
      - file2.txt
      - file3.txt

  tasks:

    - name: Create some files
      copy:
        content: "This is a standard content - {{counter}}\n"
        dest: "~/{{filename}}"
      loop: "{{remote_files}}"
      loop_control:
        loop_var: filename
        index_var: counter


#============================ SEE ALSO ===============================================

# Playbook loops
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
