
- name: Assert
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Run with items greater than 5
      command: echo {{ item }}
      loop:
        - 0
        - 2
        - 4
        - 6
        - 8
        - 10
      when: item > 5
